M48
; DRILL file {KiCad 6.0.1-79c1e3a40b~116~ubuntu20.04.1} date Sun 30 Jan 2022 02:47:47 AM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-30T02:47:47-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.1-79c1e3a40b~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X0.55Y0.1
X0.6Y2.0
X2.6Y1.4
X2.6Y0.3
T2
X0.69Y0.8241
T0
M30
